service: product-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:REGION}
  stage: ${env:STAGE}
  environment:
    PG_HOST: ${env:PG_HOST}
    PG_PORT: ${env:PG_PORT}
    PG_DATABASE: ${env:PG_DATABASE}
    PG_USERNAME: ${env:PG_USERNAME}
    PG_PASSWORD: ${env:PG_PASSWORD}

plugins:
  - serverless-plugin-webpack
  - serverless-dotenv-plugin

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: products/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
          cors: true
  createProduct:
    handler: handler.createProduct
    events:
        - http:
            path: products
            method: post
            cors: true